server.port=8080

spring.datasource.url=jdbc:mariadb://localhost:3306/RDM
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.sql.init.mode=always

spring.servlet.multipart.max-file-size=3GB
spring.servlet.multipart.max-request-size=10GB

app.storage.root-path=
app.security.admin-key-hash=
logging.level.com.example.fileserver=INFO
