CREATE TABLE IF NOT EXISTS file_entries (
    id BIGINT NOT NULL AUTO_INCREMENT,
    filesystem_id VARCHAR(64) NOT NULL DEFAULT 'default',
    entry_type VARCHAR(16) NOT NULL,
    relative_path VARCHAR(4096) NOT NULL,
    parent_path VARCHAR(4096) NOT NULL,
    name VARCHAR(512) NOT NULL,
    extension VARCHAR(64) NULL,
    mime_type VARCHAR(255) NULL,
    size_bytes BIGINT NULL,
    modified_at DATETIME(6) NOT NULL,
    created_at_fs DATETIME(6) NULL,
    is_hidden BOOLEAN NOT NULL DEFAULT FALSE,
    checksum_sha256 CHAR(64) NULL,
    last_scanned_at DATETIME(6) NOT NULL,
    db_created_at DATETIME(6) NOT NULL,
    db_updated_at DATETIME(6) NOT NULL,
    CONSTRAINT pk_file_entries PRIMARY KEY (id),
    CONSTRAINT uk_file_entries_relative_path UNIQUE (relative_path),
    INDEX idx_file_entries_parent_path (parent_path),
    INDEX idx_file_entries_name (name),
    INDEX idx_file_entries_entry_type (entry_type),
    INDEX idx_file_entries_modified_at (modified_at),
    INDEX idx_file_entries_filesystem_id (filesystem_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
